export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_CATEGORY_POSTS_SUCCESS = 'GET_CATEGORY_POSTS_SUCCESS';
export const SORT_POSTS = 'SORT_POSTS';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
